### PR TITLE
VS 2013 files

### PR DESCRIPTION
**Pull request by FreeER**

### CODE REVIEW

**Comment by ebobtron** [comment]
OK we are adding Visual Studio project files

**Comment by TsukishirOSan** [comment]
Julien,  my husband couldn't refrain from changing 2 things:
He created a visual studio project for the breakout ans added the winlibb.h
in breakout.h I want him to commit that

**Comment by TsukishirOSan** [comment]
Kinda second nature

**Comment by TsukishirOSan** [comment]
That way I can work on vs with a compiling running program. He yelled at a
few stuff "you don't commit a zip of built rmrmrmrmmumbles.
He is looking so that we use both git and vs as efficiently as possible  ☺

**Comment by ebobtron** [comment]
The commit of latest build is for those that are clueless about getting this up.  I can quickly point someone to the latest build.  My goal is to teach how easy this is once you over come some initial understanding.

Tell Julien, there is nothing conventional about me or this.

**Comment by TsukishirOSan** [comment]
I m ok with it :)
Learning to use Git and VS is... really important, create a project etc.....

2015-04-26 0:51 GMT+02:00 ebobtron notifications@github.com:

**Comment by ebobtron** [comment]
> added the winlibb.h in breakout.h 

add want he wishes, an explanation would be nice.  at this point on the project I see no need.  but a lib is not an issue.   The `WIN32_LEAN_AND_MEAN` thing is like unneeded as there isn't much need for the things we where doing when 16bit machines where around.   But I am guessing here.

This will be a full blown project with menus text screens edit boxes popups other languages and what ever we wish to explore.

**Pull request merged**
